### ISSUE TITLE
each subproject tries to create the same tag

### ISSUE THREAD

**Issue by weisebrazil** [tschulte/gradle-semantic-release-plugin#18]
If I have only sub projects, each subproject tries to create the same tag. What is the better workaround to it?

[project sample](https://github.com/weisebrazil/jenkins-pipeline)

**Comment by andreygfranca** [comment]
Is there any solution to this problem?

**Comment by andreygfranca** [comment]
@tschulte

**Comment by tschulte** [comment]
This plugin is not intended to be used on multiple projects in the same repo. Apply it to the root project only.
