### ISSUE TITLE
Customization of release task doesn't work as expected

### ISSUE THREAD

**Issue by alexsedova** [tschulte/gradle-semantic-release-plugin#19]
Hi! Thank you for the implementation of automatic semantic versioning. This plugin really looks like something we want to integrate to CD process. 
I started with integration but I fault to make work release strategy. 

We are planning to have a master branch for releases and integration branch for release candidates. Releases will be tagged by vX.Y.Z and RC by vX.Y.Z-rcN. 

Did I understand correctly this plugin could be customized to add "-rc.N" at the end of the tag if we are on integration (or any branch we want for release candidates) branch. I tried to customize the release task as it provided in the repo example, but it does not seem to work. Could you please take a look at the configuration below and point me if I use the plugin wrongly? 

```groovy
semanticRelease {
    releaseBranches {
        include 'integration'
    }
}

release {
     versionStrategy semanticRelease.releaseStrategy.copyWith(
            type: 'integration',
            selector: { state ->!state.repoDirty && state.currentBranch.name ==~ /integration.*/ &&
                        semanticRelease.semanticStrategy.canRelease(state) && project.gradle.startParameter.taskNames.find { it == 'release' }
            },
            preReleaseStrategy: {
                StrategyUtil.all({ it.copyWith(inferredPreRelease: 'rc') } as PartialSemVerStrategy, Strategies.PreRelease.COUNT_INCREMENTED)
            }
    )
}
```

Thanks a lot in advance.

**Comment by tschulte** [comment]
I just tried at https://github.com/tschulte/gradle-semantic-release-test/releases. After pushing to the rc branch, the CI server successfully published a RC-Version.

You should not call `include 'integration'`, since that would add the integration branch to the normal version strategy.

**Comment by alexsedova** [comment]
Thanks! I moved out releaseBranch block with RC-branch. 
Could you please note the version of gradle you are using for your release, because I 
have class cast exception at StrategyUtil.all(...) " > Exception thrown while executing model rule: org.gradle.api.publish.plugins.PublishingPlugin$Rules#publishing(org.gradle.api.plugins.ExtensionContainer)
   > org.ajoberstar.gradle.git.release.semver.StrategyUtil$ApplyAllChainedPartialSemVerStrategy cannot be cast to org.ajoberstar.gradle.git.release.semver.SemVerStrategyState"

**Comment by tschulte** [comment]
The sample uses gradle 3.0rc2

**Comment by alexsedova** [comment]
Hi again! I realized how to use custom strategy. It works perfectly!
I still have a couple of questions about how to some Closures are working.
Can I use the combination of two extensions? For example for my custom release version I use "release" task and define the version strategy using the extension from the semantic plugin. Now we faced a need to check a change scope to find if there are appropriate commit messages. So, I can see in the README you are describing a changeLog extension where I can call changeScope closure. First of all, is it OK to use both semanticRelease{...} and release {versionStrategy ...}? Could you please to give me a clue how I can use changeScope closure if I need to check a list of commits? Will it be called recursively? As well as id does not clear for me what a block I have to add to changeScope{ Commit commit -> ... } to get a result. This closure looks like exactly as I want to add as a checking point. I will be very appreciated for your answers. Thanks.
