### ISSUE TITLE
SSL problem

### ISSUE THREAD

**Issue by afterthought** [tschulte/gradle-semantic-release-plugin#20]
When this runs I get:

    Execution failed for task ':updateGithubRelease'.
    > javax.net.ssl.SSLPeerUnverifiedException: Host name 'uploads.github.com' does not match the     
    certificate subject provided by the peer (CN=*.githubusercontent.com, O="GitHub, Inc.", L=San Francisco, ST=California, C=US)

It seems to work. My release gets created and assets uploaded. But the gradle task fails. I've been hunting for flags to control insecure_ssl, no luck yet though.

**Comment by tschulte** [comment]
I just tried using https://github.com/tschulte/gradle-semantic-release-test. I could not reproduce the issue.

Which gradle version do you use?

**Comment by afterthought** [comment]
3.3

I just forked the same repo you mentioned and tested. Worked fine. So I retested on my project and today it worked. Maybe it was a blip on github's servers. Thanks!
