### ISSUE TITLE
Multiple commits between releases do not increment the version number as expected

### ISSUE THREAD

**Issue by nbrauer** [tschulte/gradle-semantic-release-plugin#21]
In some situation developers will commit more than one time locally before pushing to a repository. In this situation the version number is not getting incremented as expected. Example:

* Assume version is 1.0.0
* git commit -m "feat: feat1"
* git commit -m "feat: feat2"
* git push
* on CI server the branch is merged to master and ./gradlew release is executed

Expected version 1.2.0. 
*Actual version 1.1.0.*

This behavior is easily recreated locally without the use of a CI server. 

Is this expected behavior? If so, why? If not, I will investigate a code change to address this issue. Thanks!

**Comment by tschulte** [comment]
Yes, that is the expected behavor. In fact there are even tests for that.

Why do you expect the version 1.1.0 to be skipped? If you want version 1.1.0 and 1.2.0, you must push twice.

This allows to deliberately plan releases by developing on a separate branch and to release you just merge back to master and push. This way you can have multiple features and bugfixes in 1.1.0.

**Comment by nbrauer** [comment]
Excellent. Thank you very much for the explanation!
