### ISSUE TITLE
When does version inferring happen?

### ISSUE THREAD

**Issue by grv87** [tschulte/gradle-semantic-release-plugin#27]
I would like the plugin to give me changeLog for external use. I.e. for uploading to Gradle Plugins portal or Chef Supermarket.

Looking at the source I've written this spike: https://gist.github.com/grv87/8a077b55b006f5929f8c57c8ef29ce6c

The problem is that `project.version.inferredVersion` is not initialized on time for the second task:
```
gradlew B_printChangeLog
...
Build file 'R:\!spikes\semantic-release-changelog\build.gradle' line: 14

* What went wrong:
Execution failed for task ':B_printChangeLog'.
> Cannot get property 'previousVersion' on null object
```
When both tasks are run then no problem:
```
gradlew A_printVersion B_printChangeLog

> Task :A_printVersion
Inferred version: 1.0.0-SNAPSHOT
1.0.0-SNAPSHOT

> Task :B_printChangeLog
<a name="1.0.0-SNAPSHOT"></a>
## 1.0.0-SNAPSHOT (2017-10-24)

### Features

* initial commit (0ae0b06)
```

Adding `println version` to the task `B_printChangeLog` also helps.

I noticed that plugin doesn't infer version until the first task execution started. Could that be changed so that version inferring would happen before build execution or even during plugin application?

**Comment by tschulte** [comment]
Thank you for your request.

My plugin uses gradle-git. When having a look there, https://github.com/ajoberstar/gradle-git/blob/1f2c15b22e02bc930d9090d9a35f61c1af970c25/src/main/groovy/org/ajoberstar/gradle/git/release/base/BaseReleasePlugin.groovy#L79 shows that plugin does exactly, what you are doing. You don't need to `println` anything, you just need to call `project.version.toString()`. See also https://github.com/ajoberstar/gradle-git/blob/1f2c15b22e02bc930d9090d9a35f61c1af970c25/src/main/groovy/org/ajoberstar/gradle/git/release/base/ReleasePluginExtension.groovy#L97.

So to answer your question. Version inferring happens the first time someone calls `project.version.toString()`. 

In the buildscript of my plugin I have for example

```
if (!version.toString().endsWith('-SNAPSHOT'))
    publish.dependsOn publishPlugins, bintrayUpload
else if ((System.getenv('TRAVIS_PULL_REQUEST') ?: "false") == "false")
    publish.dependsOn artifactoryPublish
```

That's the exact time the version inferring happens in my plugin's build. I could add

```
project.afterEvaluate { project.version.toString() }
```

to the plugin. But I am not sure if this would not cause more harm. Anyways, this should be done in gradle-git, not my plugin. Therefore I am closing this issue.

**Comment by grv87** [comment]
OK, thanks!

I agree that `afterEvaluate` is not universal solution. In my case I need a `version` during configuration.
I just have to put
```
ext.isRelease = !version.toString().endsWith('-SNAPSHOT')
```
to the right place.

**Comment by grv87** [comment]
BTW, this works in dynamic Groovy but not in Java:
```
    def commits = semanticRelease.changeLog.commits(Version.valueOf(project.version.inferredVersion.previousVersion))
    println semanticRelease.changeLog.changeLog(commits, project.version.inferredVersion)
```
due to `SemanticReleaseChangeLogService.commits` is not public.
