### ISSUE TITLE
where can I find the .jar file associated with this project?

### ISSUE THREAD

**Issue by jpzweig** [tschulte/gradle-semantic-release-plugin#34]
Hey-- I need the jar file, I can only find the POM listed anywhere. I am trying to use this as a gradle plug-in but it is not recognizing the package anywhere... I thought it was in the /m2 feed but unable to locate.

**Comment by jpzweig** [comment]
https://plugins.gradle.org/m2/de.gliderpilot.semantic-release/de.gliderpilot.semantic-release.gradle.plugin/1.4.0/ 

There is no .jar file listed

**Comment by error418** [comment]
If you take a look into the `pom` you will notice it has one dependency to [gradle.plugin.de.gliderpilot.gradle.semantic-release:gradle-semantic-release-plugin:1.4.0](https://plugins.gradle.org/m2/gradle.plugin.de.gliderpilot.gradle.semantic-release/gradle-semantic-release-plugin/1.4.0/)

**Comment by tschulte** [comment]
What have you tried to get the plugin working? Minimal build.gradle, stacktrace, ...?
