### ISSUE TITLE
[Question] how to use on a multi-module project?

### ISSUE THREAD

**Issue by tinesoft** [tschulte/gradle-semantic-release-plugin#38]
Hi,

Thanks for this great plugin. I'm struggling to configure it to automate releasing of a multi-module project of mine (see project [here](https://github.com/tinesoft/spring-esdata-loader)).

Could document on how to setup a multi-module project? so that all artifacts (sources, javadoc, jar) produced by each sub-module, are upload to Github as well.

Thanks in advance

**Comment by tschulte** [comment]
You can do that either in the root build file:

```
allprojects { prj ->
    prj.tasks.withType(Jar) { t ->
        semanticRelease.repo.releaseAsset t, contentType: 'application/zip'
    }
}
```

Or alternatively, in the subproject you can write

```
task javadocJar(type: Jar) {
    classifier = 'javadoc'
    from javadoc
    rootProject.semanticRelease.repo.releaseAsset delegate, contentType: 'application/zip'
}
```
