### ISSUE TITLE
Multi-module build with each module having a different version.

### ISSUE THREAD

**Issue by jsmithpkp** [tschulte/gradle-semantic-release-plugin#39]
How do I configure the plugin to give each module a different version? I have found similar plugins that do handle this, by allowing each model to have its own prefix and add adding a tag for each module. None of those other plugins are as easy to use as this one.

**Comment by tschulte** [comment]
That's not possible. And I don't think it would be wise to allow that. Using the commit history to decide whether to create a version or not and whether to make it a major, minor or bugfix version does only work nicely when the whole repository is versioned as a whole. How do you want to create a tag of a repository when you only want to tag some folders?

You should really think about splitting your repositories and look into using Gradle's composite build feature.
