### ISSUE TITLE
UpdateGithubRelease breaks in Gradle 1.7

### ISSUE THREAD

**Issue by robertfmurdock** [tschulte/gradle-semantic-release-plugin#44]
Took me a week to pay attention enough to notice, but this has been blocking my automatic releases. Here's the relevant part of the build error logs.

`Some problems were found with the configuration of task ':updateGithubRelease' (type 'UpdateGithubRelease').
  - Type 'UpdateGithubRelease' property 'changeLog' is missing an input or output annotation.
    
    Reason: A property without annotation isn't considered during up-to-date checking.
    
    Possible solutions:
      1. Add an input or output annotation.
      2. Mark it as @Internal.
    
    Please refer to https://docs.gradle.org/7.0/userguide/validation_problems.html#missing_annotation for more details about this problem.
  - Type 'UpdateGithubRelease' property 'repo' is missing an input or output annotation.
    
    Reason: A property without annotation isn't considered during up-to-date checking.
    
    Possible solutions:
      1. Add an input or output annotation.
      2. Mark it as @Internal.
    
    Please refer to https://docs.gradle.org/7.0/userguide/validation_problems.html#missing_annotation for more details about this problem.
  - Type 'UpdateGithubRelease' property 'tagName' is missing an input or output annotation.
    
    Reason: A property without annotation isn't considered during up-to-date checking.
    
    Possible solutions:
      1. Add an input or output annotation.
      2. Mark it as @Internal.
    
    Please refer to https://docs.gradle.org/7.0/userguide/validation_problems.html#missing_annotation for more details about this problem.
`

**Comment by mswertz** [comment]
I have same issue. I cannot find how to fix it in the build.gradle file, so get impression it would require new release of this plugin were necessary annotations would be added (or simply make them all @internal )
